# Generated by Django 5.2.7 on 2026-03-28 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image_couverture',
        ),
        migrations.AddField(
            model_name='categorie',
            name='cover_url',
            field=models.URLField(blank=True, help_text='URL image de la catégorie'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cover_url',
            field=models.URLField(blank=True, help_text='URL image externe du plat'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cover_url',
            field=models.URLField(blank=True, help_text='URL image externe (Unsplash, etc.)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='gamme_prix',
            field=models.CharField(choices=[('$', 'Économique (< 1000 FDJ)'), ('$$', 'Modéré (1000-3000 FDJ)'), ('$$$', 'Haut de gamme (> 3000 FDJ)')], default='$$', max_length=3),
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='restaurants.restaurant')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-date_ajout'],
                'unique_together': {('utilisateur', 'restaurant')},
            },
        ),
    ]
